name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-commit:
    runs-on: macos-latest

    steps:
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Current platform versions
        run: |
          xcodebuild -version
          swift --version
          swiftlint version

      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Run lint
        run: |
          make lint

      - name: Run test
        run: |
          make test
